### ISSUE TITLE
Partial image write with [log_image]

### ISSUE THREAD

**Issue by zwade** [comet-ml/issue-tracking#278] opened 2019-08-05 19:20 UTC
We occasionally have issues with image uploading where the resulting file is partially uploaded/corrupted. This is using the python sdk. Here is an example call site

```
with torch.no_grad():
    path = run_infer(url, device, cfg, model, iteration)
    experiment.log_image(path)
```

Example experiment/asset have been reported privately

**Comment by dsblank** [comment] 2019-08-05 19:39
@zwade Is path an actual file name, or a file pointer?

**Comment by zwade** [comment] 2019-08-05 19:45
It's a path on disk

**Comment by dsblank** [comment] 2019-08-05 19:46
Is the image done being created by the time you call log_image()?

**Comment by zwade** [comment] 2019-08-05 19:49
I believe so, the image is being created via a `cv2.imwrite` call. As far as I know, this call won't return until the file has been fully written.

**Comment by dsblank** [comment] 2019-08-05 19:50
Ok, please check on your end, and we'll look into why this could happen on our side. Thanks for the information!

**Comment by zwade** [comment] 2019-08-05 19:51
Will do, thanks for all the help!

**Comment by zwade** [comment] 2019-08-05 20:10
To the best of my understanding, this is what `cv2.imwrite` is calling under the hood, which seems to write the whole file before returning.

https://github.com/opencv/opencv/blob/11eafca3e2a4cbc62f1309d25db0ea3ed9a6ea8e/modules/imgcodecs/src/grfmt_jpeg.cpp#L543

I don't observe any partial writes to disk when I run it locally, although if it were a race condition between the write and the upload I wouldn't expect to. I think its either an issue with the upload failing or I'm misunderstanding what the OpenCV code is doing.

**Comment by dsblank** [comment] 2019-08-13 08:50
Do you know what `run_infer(url, device, cfg, model, iteration)` returns?

Note that `Experiment.log_image()` has a few options, including `copy_to_tmp` which is True, and forces the image to be written to a temporary location before sending. See: https://www.comet.ml/docs/python-sdk/Experiment/#experimentlog_image for more information.

If this keeps happening, please send me a URL of such an experiment. doug@comet.ml

**Comment by gidim** [comment] 2019-08-18 20:36
@zwade  - we couldn't reproduce this in any way. There might be multiple things that can corrupt the jpeg image. Closing this for now but do let us know if you encounter the issue again.

**Closed by gidim** 2019-08-18 20:36 UTC
