### ISSUE TITLE
Chart, Code, Graph definition, and Output tabs show nothing

### ISSUE THREAD

**Issue by srafay** [comet-ml/issue-tracking#13] opened 2018-04-05 23:56 UTC
Hello, I am using this example from the docs https://www.comet.ml/docs/python-sdk/keras/#end-to-end-example
But it shows nothing after the completion on the above said tabs. Hyper-parameters, Metrics, and Installed Packages are shown correctly. 

I am using:
Python 3.5.3 
Anaconda 4.4.0 (64-bit)
IPython 5.3.0

**Comment by gidim** [comment] 2018-04-06 01:04
Are you running this from a jupyter notebook?

**Comment by jwfromm** [comment] 2018-04-06 06:08
I have the same issue when run from a jupyter notebook (I'm sure srafay is too). Is there any workaround or is Jupyter totally unsupported?

**Comment by gidim** [comment] 2018-04-06 16:27
We're looking into this. Chart and `graphdef` should work

**Comment by jwfromm** [comment] 2018-04-06 16:30
I recommend making this support high priority. Jupyter is extremely popular for ML right now and a lot of first time users of comet might be confused.

**Comment by gidim** [comment] 2018-04-06 16:37
No question about it.  Can you share a small example that reproduces the issue?

**Comment by jwfromm** [comment] 2018-04-06 18:40
Even the most basic tutorial does nothing when run in a Jupyter notebook. For example, if I run the notebook cell
```
from comet_ml import Experiment

experiment = Experiment(api_key="my_key")

hyper_params = {"learning_rate": 0.5, "steps": 100000, "batch_size": 50}
experiment.log_multiple_params(hyper_params)
experiment.log_metric("test",[5], step=0)
```
and then check my experiment, nothing shows up. Comet seems to do nothing with these calls. When the same code is run from good old fashioned python, everything works as expected.

**Comment by gidim** [comment] 2018-04-07 21:06
@jwfromm 
I could not reproduce the example you gave. Did you get the print statement `Experiment is live on comet.ml https://www.comet.ml/...` ?

The only thing that doesn't work on Jupyter is uploading the code as Jupyter does not expose that.
The rest should be working as intended.

**Comment by gidim** [comment] 2018-04-07 21:13
@srafay 

We're looking into the automatic logging issue with Jupyter but in the meantime you can manually get the keras callback and everything (except stdout/code) should work:

```
experiment = Experiment(api_key="my_key")
comet_callback = experiment.get_keras_callback()
```

and then in your `fit()` call add our callback:
```
    history = model.fit(x_train, y_train,
                        batch_size=batch_size,
                        epochs=epochs,
                        verbose=1,
                        validation_data=(x_test, y_test),
                        callbacks=[comet_callback])

```

**Comment by jwfromm** [comment] 2018-04-07 22:11
I ran the same test notebook again today and all the Comet logging worked as expected! I'm completely unsure what changed the behavior but am very glad it's working now.

**Comment by gidim** [comment] 2018-04-07 22:15
Glad to hear that. If this happens again please open an issue and we'll dig deeper.
Waiting to hear back from @srafay before closing.

**Comment by srafay** [comment] 2018-04-09 12:07
I am using IPython 5.3.0 (comes within Spyder Anaconda). I am getting parameters using `comet_callback = experiment.get_keras_callback()` as you suggested. It's giving me everything except _Code_ and _Output_. 
Thanks!

**Comment by gidim** [comment] 2018-04-11 01:53
Thanks!

**Closed by gidim** 2018-04-11 01:53 UTC
