### ISSUE TITLE
Invalid PCS configuration file

### ISSUE THREAD

**Issue by ChristianLagares** [comet-ml/issue-tracking#35] opened 2018-04-25 23:37 UTC
The following code snippet randomly generates a Validation Error.

CODE:
```
from comet_ml import Experiment, Optimizer

experiment = Experiment(api_key=API_KEY,
                        auto_param_logging=False, auto_metric_logging=False)
experiment.disabled_monkey_patching = False
optimizer = Optimizer(api_key=API_KEY)

params = """
lstm_layers_1 integer [1, 8] [8]
lstm_layers_2 integer [1, 4] [4]
lstm_units integer [32, 512] [512]
lr real [0.0001, 0.02] [0.002]
embedding integer [1, 256] [32]
activation integer [0, 2] [1]
optimizer integer [1, 4] [2]
batch_size integer [1, 128] [128]
filters integer [16, 128] [64]
kernel integer [3, 10] [10]
units integer [32, 256] [128]
"""
#optimizer.set_params_file(pcs_file)
optimizer.set_params(params)
```

OUTPUT:
```
Traceback (most recent call last):
  File "Desktop/MaterialProposal/Elementor_AutoML.py", line 31, in <module>
    optimizer.set_params(params)
  File "/home/christianlagares/anaconda3/lib/python3.5/site-packages/comet_ml/__init__.py", line 959, in set_params
    self._send_params(pcs_content)
  File "/home/christianlagares/anaconda3/lib/python3.5/site-packages/comet_ml/__init__.py", line 990, in _send_params
    six.raise_from(ValidationError(error), None) 
  File "<string>", line 3, in raise_from
comet_ml.exceptions.ValidationError: Invalid PCS configuration file, please fix it and retry.
COMET INFO: Uploading stats to Comet before program termination (may take several seconds)

```

Worth noting that the issue applies to variations (different defaults or ranges) of the same PCS input.

System Details:
* Ubuntu 16.04
* Tensorflow 1.4 
* CUDA 8.0
* cuDNN 6.0
* Python 3.5
* Comet 1.0.8

**Comment by Nimrod007** [comment] 2018-05-08 18:35
Hi @ChristianLagares - I cannot reproduce the issue locally nor on production. 
can you update comet to the latest version, launch a new run and gives us the experiment URL?

in addition please create the experiment after creating the Optimizer.

Thanks

**Comment by Nimrod007** [comment] 2018-05-08 19:53
the WS unclosed warning is entirely expected behaviour. thanks for the update. closing for now.

**Closed by Nimrod007** 2018-05-08 19:53 UTC
Labels: bug

**Comment by davidgilbertson** [comment] 2022-12-28 01:19
I'm getting hundreds of those `ResourceWarning` errors:
```
/usr/lib/python3.10/multiprocessing/popen_fork.py:66: ResourceWarning: unclosed <ssl.SSLSocket fd=119, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.17.50.31', 43600), raddr=('52.22.147.212', 443)>
  self.pid = os.fork()
```

Such that they swamp all other console output. Is this really expected behaviour?
