### ISSUE TITLE
Line Chart in main view not responding to filtering

### ISSUE THREAD

**Issue by dolhasz** [comet-ml/issue-tracking#112] opened 2018-09-13 19:47 UTC
I made a line chart in the main view and then sorted my models by optimizationId. The parameter comparison chart seems to correctly filter them, however the line chart does not. This can also be reproduced by selectively hiding experiments. This removes them from the parameter comparison chart, but does not from the line chart.

I have not checked this for the bar chart, because I'm lazy. I apologise.

**Comment by ceceshao1** [comment] 2018-09-14 12:46
Thanks for noting this @dolhasz - we'll check it out today for all chart types and see if we can reproduce!

**Comment by ceceshao1** [comment] 2018-09-14 21:27
@dolhasz - can you elaborate on what you mean by "filtering" within the line chart? What's the expected behavior for sorting your models (since sorting and filtering are two different interactions).

**Comment by dolhasz** [comment] 2018-09-24 14:13
@ceceshao1 Apologies - I should have been more clear (also sorry for late reply, I finally got a holiday in).

The expected behaviour is that my line chart only shows the experiment runs that fit my filter (in this case it's optimizationId). The sorting shouldn't really affect the graphs, sorry - I should have used the word 'filter' instead of 'sort'.

Let me know if this helps.

Alan

**Comment by ceceshao1** [comment] 2018-10-01 20:14
Hey @dolhasz - welcome back from holidays! I followed up with you on slack to get confirmation of some details.

**Comment by ceceshao1** [comment] 2018-11-07 21:08
@dolhasz - since there have been no updates on this issue, I'll be closing this issue.

Please feel free to re-open if this is still an issue for you!

**Closed by ceceshao1** 2018-11-07 21:08 UTC
Labels: bug
