### ISSUE TITLE
support for matplotlib cairo backend?

### ISSUE THREAD

**Issue by jliu** [comet-ml/issue-tracking#382] opened 2020-10-05 06:47 UTC
I'm trying to use the Cairo backend with matplotlib. The following example works with the third line commented out:

```
import matplotlib
import matplotlib.pyplot as plt
# plt.switch_backend('cairo')
from comet_ml import Experiment

experiment = Experiment(project_name='comet')
plt.plot([1, 2], [3, 4])
experiment.log_figure(figure=plt)
```

But if I un-comment it, the plot shows as broken:

<img width="964" alt="Screen Shot 2020-10-05 at 2 35 14 AM" src="https://user-images.githubusercontent.com/14934/95047088-6d718180-06b3-11eb-80cd-186df7d32fe6.png">

Is there some other way I should set this up, or is this a bug on the Comet end?

**Comment by dsblank** [comment] 2020-10-05 15:57
@jliu Thanks for reporting! Could you make a full debug log file and attach that (or send directly to doug@comet.ml if it contains private info). More details on log file:https://www.comet.ml/docs/python-sdk/advanced/#troubleshooting

**Comment by dsblank** [comment] 2020-10-05 18:04
Thanks for the logfile, @jliu . I have confirmed that this is indeed a bug. Working on a workaround, and a solution.

**Comment by dsblank** [comment] 2020-10-09 16:46
@jliu A fix for this will be included in the next version of `comet_ml` due to be released next week. Thanks again!

**Closed by dsblank** 2020-10-09 16:46 UTC
Labels: bug, sdk
