### ISSUE TITLE
Comet's InvalidAPIKey error prints the API key to any user

### ISSUE THREAD

**Issue by jerpint-mila** [comet-ml/issue-tracking#548] opened 2024-05-29 18:40 UTC
## Describe the Bug
When comet raises the `InvalidAPIKey` error, it prints in plain-text the API key currently in use. This means anyone with access to logs could obtain access to someone's API key they don't necessarily have access to.

## Expected behavior
It would be better to not print the API key in plain-text, or maybe just print the last few chars for reference to the user.

## Where is the issue?
- [x] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
you can simply raise the `InvalidAPIKey` error. When it gets called passed the actual API key, it will print the api key as plaintext. 

A scenario where this might happen:

```
from comet_ml import API
api = API()
api.get_experiment("restricted-workspace/exp/exp_id")
```

It's important here that `restricted_workspace` _actually exists_ and that you don't have permissions to it. When those conditions are met, your API key is printed in plaintext to the user in the logs because the exception is raised and your API key is passed as an argument.

It is not a good idea to have API keys be written in logs. This could be true of an environment with API keys being set as secrets for example.

**Comment by dsblank** [comment] 2024-05-30 12:42
@jerpint-mila Indeed, we have gone to quite some length to make sure that the API key does not appear in the logs. So this must be an oversight. I'll try to replicate and report to the engineering team. Thanks for reporting!

**Comment by dsblank** [comment] 2024-06-06 20:17
What version of of comet_ml are you using? I can't reproduce with comet_ml 3.41.0

**Comment by jerpint-mila** [comment] 2024-06-07 13:41
```
$ pip freeze | grep comet
comet-ml==3.41.0
```

**Comment by dsblank** [comment] 2024-06-11 11:04
We've been able to reproduce this and we are working on a fix.

**Comment by dsblank** [comment] 2024-06-17 12:04
A fix is being developed.

**Comment by dsblank** [comment] 2024-07-05 14:08
This is tracked as CM-10709 and a fix should be released in the next SDK version.

**Comment by dsblank** [comment] 2024-07-26 10:58
This fix has been released in the latest comet_ml. Thanks for reporting, and let us know if you have any other issues.

**Closed by dsblank** 2024-07-26 10:58 UTC
Labels: bug
